apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ovs
  template:
    metadata:
      labels:
        app: ovs
    spec:
      containers:
      - name: ovs
        image: vijetavernekar/ovs:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/vegetablesdb
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
