apiVersion: apps/v1  # stable API for Deployments
kind: Deployment     # Deployment is a k8s object that manages pods
metadata:            
  name: ovs-app      # Deployment name
spec:
  replicas: 3        # Run specified copy of application pods
  selector:
    matchLabels:
      app: ovs       # specifies which pod belong to this deployment
  template:
    metadata:
      labels:
        app: ovs     # Ensures the pods created have the lable app=ovs
    spec:
      containers:
      - name: ovs    # container inside the pod is ovs
        image: vijetavernekar/ovs:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/vegetablesdb
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
